---
title: "Cognitive Domains V2"
author: "Jeremy Elman"
date: '`r Sys.Date()`'
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    theme: readable
  word_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r, include=F}
library(dplyr)
library(psych)
library(knitr)
```



```{r, include=F}
setwd('K:/Projects/Cognitive Domains')

vetsa2CogDomains = read.csv("./data/V2_CognitiveDomains.csv", stringsAsFactors = F)

cogDomainVars = c("zVisSpat_v2","zSTWKMem_v2","zEpsMem_v2","zAbsReason_v2",
                  "zVerbFlu_v2","zExecTrailsSwitch_v2","zExecCategorySwitch_v2",
                  "zExecInhibit_v2","zProcSpeed_v2")

# Processing Speed Domain 
procSpeedVars = c("zstrwraw_v2","zstrcraw_v2","ztrl2tran_v2","ztrl3tran_v2")

# Eisodic Memory Domain 
epMemVars = c("zcvatot_v2","zcvsdfr_v2","zcvldfr_v2","zlmitot_v2",
              "zlmdtot_v2","zvritot_v2","zvrdtot_v2")

# Short-Term Memory/Working Memory Domain 
stmVars = c("zdsfraw_v2","zdsbraw_v2","zlntot_v2","zsspfraw_v2",
            "zsspbraw_v2","zrsatottran_v2")

# Verbal Fluency Domain 
vfVars = c("zlfcor_v2","zcfcor_v2")

# Visual Spatial Domain 
visSpatialVars = c("zHFTOTCOR_v2","zMR1COR_v2")

# Make list of domain variables
domains = list("Processing Speed" = procSpeedVars,
               "Episodic Memory" = epMemVars,
               "Short-Term Memory" = stmVars,
               "Verbal Fluency" = vfVars,
               "Visual Spatial" = visSpatialVars)
```

**Variable names comprising cognitive domains**
```{r, echo=F}
# Print out tests within each cognitive domain
for (i in names(domains)){
  cat(i,":", domains[[i]], "\n")
}
```


```{r, echo=F}
# Descriptives of cognitive domain scores
kable(describe(vetsa2CogDomains[cogDomainVars], fast=T),
      caption='Descriptive statistics of V2 Cognitive Domains')
```

```{r, echo=F}
# Correlation between domains
cormat = cor(vetsa2CogDomains[cogDomainVars], use="pairwise.complete.obs")
cor.plot(cormat, main="Correlation of Cognitive Domains", numbers=T)
```

Alphas of cognitive domains
```{r, echo=F}
## Calculate Alphas ##

# Remove domains comprised of only a single measure
# Note: This should not be contained in V2 dataset, this code kept for 
# consistency with V1 code
compositeDomains = names(domains)[!names(domains) %in% c("Verbal Ability")]

# Create dataframe of domain alpha results
alphaSummary = data.frame()
for (domain in compositeDomains){
  alphaStat = alpha(vetsa2CogDomains[domains[[domain]]])$total
  alphaSummary = rbind(alphaSummary, cbind(Domain=domain,alphaStat))
}

kable(alphaSummary, digits=3, caption='Alphas of V2 Cognitive Domains')
```

