---
title: "Cognitive Domains V1"
author: "Jeremy Elman"
date: '`r Sys.Date()`'
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    theme: readable
  word_document: default
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r, include=F}
library(dplyr)
library(psych)
library(knitr)
```



```{r, include=F}
setwd('K:/Projects/Cognitive Domains')

# Read in cognitive domain data
vetsa1CogDomains = read.csv("./data/V1_CognitiveDomains.csv", stringsAsFactors = F)

# Select domain scores
cogDomainVars = c("zVisSpat", "zSTWKMem", "zEpsMem", "zAbsReason",
                  "zVerbFlu", "zExecTrailsSwitch", "zExecCategorySwitch",
                  "zExecInhibit", "zProcSpeed")

# Processing Speed Domain 
procSpeedVars = c("zstrwraw","zstrcraw","ztrl2tran","ztrl3tran")

# Episodic Memory Domain 
epMemVars = c("zcvatot","zcvsdfr","zcvldfr","zlmitot",
              "zlmdtot","zvritot","zvrdtot")

# Short-Term Memory/Working Memory Domain 
stmVars = c("zdsfraw","zdsbraw","zlntot","zsspfraw",
            "zsspbraw","zrsatotrevtran")

# Verbal Fluency Domain 
vfVars = c("zlfcor","zcfcor")

# Visual Spatial Domain 
visSpatialVars = c("zHFTOTCOR","zMR1COR")

# Make list of domain variables
domains = list("Processing Speed" = procSpeedVars,
               "Episodic Memory" = epMemVars,
               "Short-Term Memory" = stmVars,
               "Verbal Fluency" = vfVars,
               "Visual Spatial" = visSpatialVars)

```

**Variable names comprising cognitive domains**
```{r, echo=F}
# Print out tests within each cognitive domain
for (i in names(domains)){
  cat(i,":", domains[[i]], "\n")
}
```


```{r, echo=F}
# Descriptives of cognitive domain scores
kable(describe(vetsa1CogDomains[cogDomainVars], fast=T),
       caption='Descriptive statistics of V1 Cognitive Domains')
```


```{r, echo=F}
# Correlation between domains
cormat = cor(vetsa1CogDomains[cogDomainVars], use="pairwise.complete.obs")
cor.plot(cormat, main="Correlation of Cognitive Domains", numbers=T)
```

```{r, echo=F}
## Calculate Alphas ##

# Create dataframe of domain alpha results
alphaSummary = data.frame()
for (domain in names(domains)){
  alphaStat = alpha(vetsa1CogDomains[domains[[domain]]])$total
  alphaSummary = rbind(alphaSummary, cbind(Domain=domain,alphaStat))
}

# Print summary of alphas
kable(alphaSummary, digits=3, caption='Alphas of V1 Cognitive Domains')

```


